### ISSUE TITLE
Deck Shuffle routine in Section 3.03

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#107]
The list call needs to added for the range function in shuffled_deck() looks correct, :

import random
def shuffled_deck ():
    basic_deck = list(range(2,15)) \* 4
    random.shuffle(basic_deck)
    return basic_deck
shuffled_cards = shuffled_deck()
for i in shuffled_cards:
    print (i)

**Comment by kenneychan** [comment]
Fixed list call in Lab 3.03
