### ISSUE TITLE
Lab 3.03 War Game - How does it play?

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#111]
The rules state that there is a "while loop that keeps the game running until there are no cards in the deck". Does this mean there is one pass thru the deck and whoever has the most cards wins? What if there is a tie (assuming the top two cards are played from the deck)? Take the next two cards an whoever wins that gets all four cards (including the previous tied cards)?

**Comment by kenneychan** [comment]
The War game rules for tie and who wins has been clarified.
