### ISSUE TITLE
Function Contract

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#113]
I think a better format for the function contract would be:
# Name:      my_function4
# Purpose:  Adds two integer numbers together
# Inputs:      Two integers
# Returns:   Integer sum of the 2 inputted integers

Could expand Inputs/returns to include variable name (s), type(s) and a comment.

We also put in 
       Author, 
       Date, and 
       History of changes (for maintenance) - date , author, comment

**Comment by kenneychan** [comment]
Update Lesson 3.01, 3.02, Lab 3.03 with function contract: Name, Purpose, Inputs, Returns

**Comment by kenneychan** [comment]
Closed
