### ISSUE TITLE
Row, Column exchanged in Tic-Tac-Toe solution

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#119]
When I run the Tic-Tac-Toe.py file, I enter:
 2 for " which column would you like? "
 1 for " which row would you like? "
 Which results in:
##      |    | 

```
 |    | 
```

---

```
 |x   |  
```

It should be  (leftmost column and middle row(
##      |    | 

```
 |    | x
```

---

```
 |    |  
```

I believe the problem is user_y and user_x should be exchanged at the point in code which solicits input.

**Comment by kenneychan** [comment]
Solution to Lesson 4.06: Project 4 has been fixed
