### ISSUE TITLE
Error with print_attacks in solution for Pokemon on TEALS site

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#126]
In the solution for Pokemon on the TEALS protected site for 2nd semester, the lines:

   print_attacks(player)
   print_attacks(computer)
give errors:

Traceback (most recent call last):
  File "/home/ubuntu/workspace/python/pokemon.py", line 128, in <module>
    game_loop()
  File "/home/ubuntu/workspace/python/pokemon.py", line 125, in game_loop
    print_attacks(player)
NameError: name 'print_attacks' is not defined

**Comment by kenneychan** [comment]
Solution was posted as the starter code on the gitbook and the starter code was posted to the solutions directory.  I swapped the two files so they should be correct now

**Comment by kenneychan** [comment]
Solution was posted as the starter code on the gitbook and the starter code was posted to the solutions directory. I swapped the two files so they should be correct now
