### ISSUE TITLE
Starter code missing for Pokemon

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#128]
For project 7 Pokemon the code pointed to by starter_code is missing. See:

Implementation Details

Use classes to build off the implemented base class for Pokemon. Keep track of HP, Max AP, and type.
starter_code

**Comment by kenneychan** [comment]
Update path to starter_code to use absolute path

**Comment by kenneychan** [comment]
Update path to starter_code to use absolute path

**Comment by normanbauer** [comment]
I used the TEALS dashboard to get to the 2nd semester material.  I went to Project 7: Pokemon and to the starter_code link under Implementation Details. Nothing appeared to happen.  No tab with the code in it or in my download directory. However if I right click on the link and select open in new tab or window I get a Pokemon file which appears to be the total solution.

**Comment by kenneychan** [comment]
Looks like the solution was posted to the github and the sample code was posted to the dashboard.  I swapped the two files so now the sample code should show up on the git book and the solution is on the dashboard.l

**Comment by normanbauer** [comment]
Yep it works, close the puppy out.
