### ISSUE TITLE
Unit 8 - Final Project Organizer and Final Project Development links not found.

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#129]
In Unit 8, the Final Project Organizer and Final Project Development links not found. From the browser nothing happens, when I cut and paste the URL, I get a 404 - Filr not found.

Link: https://teals-introcs.gitbooks.io/2nd-semester-introduction-to-computer-science-pri/content/units/final_project_development_plan.docx

Link: https://teals-introcs.gitbooks.io/2nd-semester-introduction-to-computer-science-pri/final_project_plan_organizer.docx

**Comment by kenneychan** [comment]
Updated links to project files
