### ISSUE TITLE
Correct sentence in Introduction, Python Versions (2 vs 3) paragraph

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#131]
The senternce 
"Just as a car part from a 10 year old model car will probably not fit a new model of the same car, Python 2 code probably not run in a Python 3 environment."

is missing a should, the sentence should read:

"Just as a car part from a 10 year old model car will probably not fit a new model of the same car, Python 2 code probably **would** not run in a Python 3 environment."

**Comment by kenneychan** [comment]
Grammar fixed: added "would"
