### ISSUE TITLE
Lesson 4.05 - Code Example - What is its purpose?

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#134]
The code example is:

def boxes_to_buy(num_needed, sizes):
    result = {}
    remaining = num_needed

    for size in sizes:
        result[size] = remaining // size
        remaining = remaining % size

    if remaining > 0:
        result[min(sizes)] += 1  # add one of the smallest pack-size if there are any left :)

boxes_to_buy(96, [3, 5, 7])

Thew way it is coded (with the smallest box size first), the smallest size will get the entire allocation (32 boxes).  It would be much bette to have the arguments like (96, [20,5,3]) to have a much better distribution. Even better would be to use the biggest box first, then next biggest, etc. In real life, you would want as few boxes as possible and as box sizes big as possible. 
Is the purpose of the exercise to have students discuss and analyze  what is happening?  To make a better allocation of boxes?

**Comment by kenneychan** [comment]
Yes, in real life you would want as few boxes as possible.  The sample data has been updated to boxes_to_buy (96, [20,5,3]).
