### ISSUE TITLE
Associated Readings Unit 5 and 6 really refer to Units 6 and 7 of the Python material

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#136]
Te associated readings and its subsections are mislabeled ad Unit 5 and 6.  They should be 6 and 7 to align with the curriculum.  The references in the text do point to 5 and 6, not 6 and 7.  Just a little confusing labelling.

**Comment by kenneychan** [comment]
Renumbered Unit 5, 6 reading to Unit 6, 7 to match curriculum.
