### ISSUE TITLE
Solution to Kangaroo class lab 7.03

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#137]
[kangaroo.txt](https://github.com/TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles/files/679139/kangaroo.txt)

**Comment by kenneychan** [comment]
7x03_lab_solution.py has been added to the TEALS dashboard Intro 2nd Semester Protected Materials.
