### ISSUE TITLE
Lab 1.03 clarification

### ISSUE THREAD

**Issue by smeredith** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#138]
Here are what the results, but not the source code, will look like.
    
    Zero is 0
    One is 1
    Two is 2
    Three is 3
    Four is 4

Is "One is 1.0" a valid answer? If so, maybe we should clarify that in the lab. If not, are casts to int allowed? (They haven't been covered yet.) If not, is there a way to get the integer value 1 using 4 4s?

**Comment by kenneychan** [comment]
Trailing 0s are fine.  The lesson plan has been updated to explicitly state trailing 0s are OK due to floating point arithmetic.
