### ISSUE TITLE
Use of  wireframe in Do Now 8.01

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#139]
In the Do Now 8.01 there is the sentence:

"Sketch - Draw a very basic wireframe sketch of the main "screens" of the app"

I thought since this is a text based language, there would be scenarios, not "screens"

**Comment by normanbauer** [comment]
Wireframing is also mentioned in Defining Requirements 8.2 (should be flowchart?)

**Comment by kenneychan** [comment]
Fixed references to wireframing to flow chart
