### ISSUE TITLE
Do we really want to teach globals in Lesson 3.04?

### ISSUE THREAD

**Issue by smeredith** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#158]
The instructors notes in 3.04 do not cover the concept of global variables well. The "global" keyword is not even mentioned in the "Associated Reading" at all. If we want to talk about globals at this point, I think we should skip the keyword. I'd prefer if my students didn't use globals at all. Start good habits early.

**Comment by smeredith** [comment]
I guess teaching globals is fine, but maybe we can skip the "global" keyword.

**Comment by kenneychan** [comment]
Hi Steve,

I put context around the global section that they are often used for constants.  I added the reading section on global variables to section 3.4.  Since the "global" keyword is required to access a global variable, it was not possible to skip the "global" keyword.
