### ISSUE TITLE
Project 1.06 MadLibs project spec needs more instruction

### ISSUE THREAD

**Issue by smeredith** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#167]
Some of our students didn't understand that they were supposed to create their own story. They tried to use the example story.

Also, in the intro: "You will also practice designing a project by planning out your Mad Lib before implementing it." This should probably be stressed a little more in the instructions: plan out your story first, before you start implementing the program.

**Comment by kenneychan** [comment]
Add instruction around student's creating their own story.  Add planning guildline
