### ISSUE TITLE
Lab 7.04: is Water Type supposed to override growl()?

### ISSUE THREAD

**Issue by smeredith** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#169]
The base class has `growl()`, and the other two derived types also have `growl()`. But the Water Type derived class has `splash()` instead. I wonder if this is a mistake and it is supposed to have `growl()` instead of `splash()`?

**Comment by kenneychan** [comment]
Yes this looks like a mistake and should override growl().  7.04 has been fixed.
