### ISSUE TITLE
Link problems on all of Unit 1

### ISSUE THREAD

**Issue by osteenjp** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#19]
Links within lesson plans direct to file not found.

**Comment by TEALS-IntroCS** [comment]
Link issues we found so far:
incorrect path.
Path is RELATIVE, so within a folder for a lesson, just need the file name
Make sure there is no extra whitespace

**Comment by TEALS-IntroCS** [comment]
Links must appear in the table of contents (SUMMARY.MD) or they will open as a download.
