### ISSUE TITLE
Lesson Plan 3.03 Accommodation/Differentiation - Deal function?

### ISSUE THREAD

**Issue by osteenjp** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#22]
Is this is a typo? I'm not sure what the deal function is and couldn't find it after doing some web searching.

**Comment by goldblatt** [comment]
yup written in python2 will convert over

**Comment by goldblatt** [comment]
actually this looks like the wrong version. I definitely was able to play ....

**Comment by goldblatt** [comment]
should have been the shuffle function
