### ISSUE TITLE
Bugs in Oregon Trail Project 3.05

### ISSUE THREAD

**Issue by osteenjp** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#24]
Tried running the example code and ran into some errors. 

Tried fixing and hit some snags. Didn't have time to really go through this and fix all bugs.

**Comment by goldblatt** [comment]
whoops there was a typo and I wrote in python2. the changes to python3 make it a bit more complicated, as you have to pass around a list of values to each function...but I updated and it runs fine now. I had tested it before putting it into the curriculum. not sure what happened.
