### ISSUE TITLE
Do Now 4.02

### ISSUE THREAD

**Issue by osteenjp** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#25]
Is it supposed to be print(range(0,10))? When I type the code for both part 1 and 2 nothing happens.

**Comment by goldblatt** [comment]
oh this is a difference between python2 and python3-- range is a generator in python3 and in python2 it's a list. sorry forgot about this. need to think about best way to deal with

**Comment by goldblatt** [comment]
okay fixed
