### ISSUE TITLE
LP 1.01 - new page called "2 ways to submit work"

### ISSUE THREAD

**Issue by TEALS-IntroCS** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#3]
Page details two suggestions for having students submit work via cloud9:
1) shared workspace, and then your Learning Management System just has a form they submit saying "I'm done" and/or asking reflection questions

2) students download files from cloud9 to local machine and then upload/submit those files to a learning management system (canvas, google classroom, etc)

**Comment by goldblatt** [comment]
added this to the IDE signup teaches file
