### ISSUE TITLE
Associated Reading - Lesson 1.02

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#34]
Under Operators and Operands in Associated Reading - Lesson 1.02,

"20+32 hour-1 hour60+minute minute/60 5**2 (5+9)(15-7) In some other languages, ^ is used for exponentiation, but in Python it is a bitwise operator called XOR."

Exponentiation should be the *\* operator.  Also the next sentence starts with "I will...".  I don't think you want to use the personal pronoun I in this context.

**Comment by goldblatt** [comment]
done
