### ISSUE TITLE
python 3 under Could 9, / and // appear to return the same floor result

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#35]
print (7//-3)
print(7/-3)
-3  
-3

**Comment by normanbauer** [comment]
Floor division differs from regular division when one of the numbers in division is a floating point:

print (7.5//-3)
print(7.5/-3)
-3.0  
-2.5 

I would think of it (//) as 
floor(a/b)

**Comment by TEALS-IntroCS** [comment]
We don't reproduce this issue: When we do "7/-3" we get -2.5. Are you sure you're using Python 3?

**Comment by normanbauer** [comment]
I get two different results:

normanbauer:~/workspace (master) $ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > print (7//-3)
> > > -3
> > > print (7/3)
> > > 2.3333333333333335

In the file mode under Cloud9:

print (7//-3)
print(7/-3)

produces:

Your code is running at https://demo-project-normanbauer.c9users.io.  
Important: use os.getenv(PORT, 8080) as the port and os.getenv(IP, 0.0.0.0) as the host in your scripts!                                                                                                    

-3  
-3   

Looks like there is a difference between interactive and file mode.
