### ISSUE TITLE
Lesson 3.4: Naming Conventions and Globals

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#36]
Is there a section on naming conventions, especially as they apply to "industry standards" for ease of reading and getting used to coding in a "production" environment?

Also there should be a discussion of globals and maybe the convention of starting globals with "g_".

Conventions for naming Constants, variable names (use of "_"), methods/functions, etc.

**Comment by TEALS-IntroCS** [comment]
Let's add a NOTE to instructors that we are using the convention of all caps for global variables. They can discuss the idea of a naming convention (it's a soft a rule to help make code more readable). Another naming convention for globals would be g_[variable name]

**Comment by normanbauer** [comment]
Agree, there also could be naming conventions for functions so they stand out such as the camelCase notation.

**Comment by goldblatt** [comment]
done
