### ISSUE TITLE
Lesson 1.02: UNIX/Linux and  Python Interactive commands

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#37]
You introduce the Bash shell, perhaps a little intro on UNIX commands might be in order. I know our students need background.

Example:  using the interactive screen, user can enter cntrl D or exit() to exit the Python interpreter and get into the Bash shell. Entering the Bash command "clear" will clear the screen and entering python3 will get the user back into the interpreter with a clean screen.

To edit a python command interactively, you can use the up  arrow to get to a previous command and left, right keys to move within the command. The delete key removes characters and typing will insert new characters. 

I would suggest a minimal cheat sheet of UNIX/Bash commands as well as editing keys for the interactive interpreter. I know my students would get lost quickly. Perhaps a lesson?

**Comment by TEALS-IntroCS** [comment]
Let's add a link to a UNIX/Bash cheat sheet as an optional material in this lesson. Make sure it actually is valid for Cloud9 environment. And note somewhere in materials that these commands probably don't work if you are using Python installed on Windows (but they might work in IDLE).

**Comment by normanbauer** [comment]
Since you are running on the web, wouldn't the commands be processed on the web, i.e., independent of the terminal/browser you are running on? Isn't IDLE is a local processor and might not support UNIX commands under Windows?

**Comment by TEALS-IntroCS** [comment]
Yes- but we expect some classes will probably do a local install of Python rather than using Cloud9. So we want to note that if they have gone that route, the UNIX/Bash commands may not work, depending on what they are using.

**Comment by goldblatt** [comment]
okay this should be good created a cloud_9_cheat_sheet referenced by 1.02 and 1.03

**Comment by normanbauer** [comment]
Great!!!  You are a super woman.  Aren't you watching the National Championship Football Game?

**Comment by goldblatt** [comment]
Hahaha I don't even know who is playing (go sports!), just trying to catch
up on the stuff I planned to get done today :)

On Mon, Jan 11, 2016 at 11:51 PM, normanbauer notifications@github.com
wrote:

> Great!!! You are a super woman. Aren't you watching the National
> Championship Football Game?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles/issues/37#issuecomment-170790844
> .

## 

-Susan Goldblatt
