### ISSUE TITLE
Python "input" command works differently in the interactive mode and the file mode

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#38]
In the file mode, if the input string is not enclosed in quotes, it is interpreted as a Python 
 command, not an input string. 

In the interactive mode, input  acts as a string input, not requiring the string to be enclosed in quotes.  

The command raw_input acts as a string input without requiring quotes. The command raw_input is not defined in the interactive mode.

The "input" command allows you to enter Python commands by typing which is a very clever way of programming. If you enter bill Python treats it as a variable, if you enter "bill" it is treated as a string and the quotes are kept.

**Comment by goldblatt** [comment]
that has been switched in python3 so there is no raw_input in python3 and input automatically takes in stdin as a string.
