### ISSUE TITLE
General Comment - Software Engineering

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#39]
I would like to see more emphasis on software design and problem solving. As has been discussed on TEALS piazza, most people taking computer science will not become programmers. 

But the problem solving skills would always be useful. I have students tell me "I don't where to begin". 

Addressing this issue with some paradigm such as abstraction and top down design would be of great benefit.  Of course you still need the tool box of code to implement the design. 

Examples such as the Fibonacci numbers and building triangles using the print command would be enlightening.

**Comment by TEALS-IntroCS** [comment]
This isn't an actionable suggestion. All of our labs and projects involve problem-solving. We've included specific labs and lessons on debugging. We can also add the "4 Steps to Solve Any Problem" handout into the materials.
