### ISSUE TITLE
Programming Jokes - You might include these as a lighter touch

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#42]
"A program is like a nose; sometimes it runs, sometimes it blows. " 
- Howard Rose - As quoted in Computer Lib, 1987 printing, page 42

Actually I read this in a "Datamation" magazine in 1968.

A doctor, an engineer were arguing over what is the oldest profession.
The doctor said doctoring is the oldest, God made Eve out or Adam, a great medical feat.
No said the engineer, engineering is the oldest, God created Heaven and Earth out of Chaos.
The programmer said, who do you think cerated Chaos?

**Comment by TEALS-IntroCS** [comment]
Can you suggest lessons where these jokes might be appropriate? Reopen with comment :)

**Comment by normanbauer** [comment]
The nose joke would be good to open the first discussion of debugging. 

The oldest profession one would be good when doing the programming as a career pitch.
