### ISSUE TITLE
Lesson 2.01 Binary Day - Suggestion for Demo

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#43]
I would suggest an unplugged version of how a fax works sending 0, 1 and line feed.

Have the student draw a 5 X 15 grid on the board.  From the top left either fill in the square (send 1) and advance or just advance (send 9) or send a line feed to go to the beginning of the next line. 

![image](https://cloud.githubusercontent.com/assets/16528654/12103832/b059a6d8-b2fa-11e5-9c0e-041e78517d75.png)

This would demonstrate how 0s and 1s (and a line feed) can display intelligible information.  It would also show how a black and white fax machine operates.

**Comment by TEALS-IntroCS** [comment]
There's a great variety of potential Binary activities. We can't include them all in the lesson. If you'd like, write this up in a Word Document in more complete form and we can add it to the Supplementary Curriculum Materials. Separately, we'll add a note to lesson 2.01 suggesting that there are many additional binary activities one could try.
