### ISSUE TITLE
Associated Reading 2.03 - Logical operators section

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#45]
the line:

n2 == 4 or n 10 == 100 is true if either of the conditions is true, that is, if the number is 2 or 1

should read 

n_2 == 4 or 10_*n == 100 is true if either of the conditions is true, that is, if the number is 2 or 1

It might be worth mentioning that and OR expression is true whenever one of the operands is true and an AND expression is false whenever one of the operands is false.

**Comment by goldblatt** [comment]
fixed!
