### ISSUE TITLE
Quizzes need to be hidden

### ISSUE THREAD

**Issue by TEALS-IntroCS** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#46]
Currently students will have access to the quizzes!

**Comment by TEALS-IntroCS** [comment]
Also need to think about the GitHub repo. If the source files are in there and the repo is open, students can find it.

**Comment by osteenjp** [comment]
Same is true for the example code for each end-of-unit project, probably don't want students having access to that code.

**Comment by TEALS-IntroCS** [comment]
Solution:
1. Create Word/PDF docs of quizzes
2. Upload quizzes and all solutions to labs/projects to SharePoint Additional Curriculum Materials library
3. Remove all said materials from gitbook and GitHub and replace with note about finding materials via TEALS Dashboard "Additional Curriculum Materials"
4. Expunge revision history of these files from GitHub

**Comment by goldblatt** [comment]
working on this. got the pdf to quizzes and the quizzes/solutions uploaded and removed from the git with links to the solution

**Comment by goldblatt** [comment]
Alright this is done. let me know if there are any issues.

**Comment by TEALS-IntroCS** [comment]
From last night's piazza thread: Quizzes should not be direct links to SharePoint. Folks can only access SharePoint by visiting the TEALS Dashboard and clicking on the "Additional Curriculum Materials" link (which is a special link that grants access to SharePoint).

I'd suggest something like:
Quiz [access protected resources by clicking on "Additional Curriculum Materials" on the TEALS Dashboard]

and "TEALS Dashboard" can be a link to www.tealsk12.org/dashboard

**Comment by goldblatt** [comment]
Are you positive the link says anyone with the the link can view as long as they are logged in? it worked fine for me ....

**Comment by TEALS-IntroCS** [comment]
I think you were probably already authenticated via the special link on the dashboard. The "anyone with the link can view as long as they are logged in" means that if you are logged in to sharepoint (which volunteers can only do by first going through the Dashboard), then the link will work. But they have to first go through the dashboard to get the auth cookie.

**Comment by goldblatt** [comment]
okay switched it. also it was because the link takes you to microsoft online, so I had the login credentials for that, but we don't give those to everyone
