### ISSUE TITLE
Confusion over Project 4 - Tic-Tac-Toe

### ISSUE THREAD

**Issue by osteenjp** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#48]
Is it supposed to be a complete game or not? The project description was written in a way that led me to believe that it is, so that was the assumption I was riding on when editing the content of the project spec. The demo last night seemed to indicate that creating the "checker" is the only goal of the project. 

Need clarification here ASAP

**Comment by goldblatt** [comment]
Yeah I was wrong in the meeting. it is the full game. I fixed the solution so it's the whole game. sorry about that.
