### ISSUE TITLE
"Associated Reading" parts are greyed-out/inaccessible

### ISSUE THREAD

**Issue by xenotropic** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#50]
They were working yesterday -- and the first one, 3.2.2. was useful for class this morning  -- but in both Firefox and Chrome the table of contents entries for all the associated reading are grayed out and inaccessible.

**Comment by goldblatt** [comment]
Hey we moved all the associated readings into a single file (https://teals-introcs.gitbooks.io/2nd-semester-introduction-to-computer-science-pri/content/readings.html). The idea is that the readings are more textbook style and less handout style (and also that they all can be update in one place)

**Comment by xenotropic** [comment]
Ok, thanks for letting me know -- however, that is not apparent from the book itself, especially in the left side nav bar where they appear as these gray/inaccessible links (although I now see that "Associated Reading" is all the way at the bottom, which is a working/live link). "Curriculum Map" and "Summary" are similarly grayed out in the nav bar, I presume from a similar re-org.

**Comment by TEALS-IntroCS** [comment]
Solution: Removiing "Curriculum Map" from TOC until it is ready.

**Comment by goldblatt** [comment]
alright all done for now
