### ISSUE TITLE
Do Now 2.07  loops indefienitely

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#52]
The 

while True:
     print ('a')

loops indefinitely.  It is hard to kill and ties up resources.  Perhaps instructions on how to kill it would be appropriate.

**Comment by normanbauer** [comment]
I used the x button for the terminal window to kill it.

**Comment by goldblatt** [comment]
hahah i kind of like the idea that students are stuck in a program and they have to think about why and what's happening
