### ISSUE TITLE
Lesson 3.01 Definition of function

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#54]
Statement:
Function: a named sequence of statements that performs a computation.

Functions can perform other operations such as parsing, graphics, etc.

It would be better to define it more generally as performing computation, graphics, or other intended purposes.

**Comment by normanbauer** [comment]
Also 
Functions have a contract: you write down the arguments, their type, and the return type expected. The return value is optional.

**Comment by TEALS-IntroCS** [comment]
Function: a named sequence of statements. You can use functions to perform complex calculations, graphical operations, and various other purposes. When you define a function, you specify the name and the sequence of statements. Later, you can “call” the function by name. 
◾In SNAP! functions are blocks.
◾A function definition is like a contract: you tell the programmer what elements the function expects (name and type of arguments) and the function will perform its purpose. It is good practice to use a comment to specify the purpose and contract of a function, including the _type_ of value it returns, if it returns a value
◾We have already gotten used to calling functions like  type()  and  print() .

**Comment by goldblatt** [comment]
done
