### ISSUE TITLE
Lab 3.01 Magic 8-Ball (Bonus)

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#55]
Bonus! states:
"Research the math library and create a program that finds the length of a triangle given two sides."

To solve a right triangle, use Pythagorean theorem.

For non-right (oblique) triangle you need (to get all three sides and three angles):

Two sides and an angle opposite one of the known sides
Two angles and any side
Two sides and their included angle
All three sides

**Comment by goldblatt** [comment]
okay fixed to use just right triangle.
