### ISSUE TITLE
Lesson 3.02 Instructor's Notes - Abstraction

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#56]
"Ask students to brainstorm why, in general, a function might be useful in programming.
       Abstraction: managing the complexity of a program.
       Less repeated code.
       Consolidation of understanding."

Not sure what "Consolidation of understanding" means.  
I think abstraction should emphasize the removal of details and pushing the details down to a lower level. I think this should relate as a tool to software engineering and problem solving. 
Also makes code easier to read (later maintenance) and better documents the program.

**Comment by TEALS-IntroCS** [comment]
◾Abstraction: managing the complexity of a program by removing details and pushing them down to a lower level
◾Less repeated code.
◾Breaking the problem up into smaller pieces and solving each piece

**Comment by goldblatt** [comment]
done
