### ISSUE TITLE
Lesson 1.05: Indent errors in Python3

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#57]
An extra space in a line can cause an "IndentationError: unindent does not match any outer indentation level"

This can be hard to find.  There is help using python3 in the interactive window:

python3 -m tabnanny input.py

where input.py is the python source file having the unident error. The output will help you find the error. 

Suggest using the tab key to indent and the shift tab to remove an indent.

**Comment by TEALS-IntroCS** [comment]
Let's add this tip in the first debugging lesson.
