### ISSUE TITLE
Lab 3 Example does not work

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#59]
The second item under Aliasing 
 # input: a list of ints
 # output: an int
 def update_list(a_list): 
       if len(a_list) > 5: 
           a_list[3] = "yo"
           b = a_list[4]
           c = a 
       return c
   my_list = [1, 2, 3, 4, 5]
   update_list(my_list)

fails

Traceback (most recent call last):  
  File "/home/ubuntu/workspace/python/test3.py", line 17, in <module>  
    print (update_list(my_list))  
  File "/home/ubuntu/workspace/python/test3.py", line 15, in update_list  
    return c  
NameError: global name 'c' is not defined

My version:
 # input: a list of ints
 # output: an int
def update_list(a_list): 
    if len(a_list) > 4: 
         a_list[3] = "yo"
         b = a_list[4]
    return
my_list = [1, 2, 3, 4, 5]
print (update_list(my_list))
print(my_list)

But maybe hahaha - let them eat cake

**Comment by normanbauer** [comment]
The Lab should be  LAB 3.04

**Comment by goldblatt** [comment]
alrighty fixed this!

**Comment by normanbauer** [comment]
I really want to help you guys. I am a volunteer, not getting paid for this.

**Comment by goldblatt** [comment]
it's super helpful!!!!

**Comment by normanbauer** [comment]
I am retired, and enjoy doing this.  Besides it keeps me from bickering with the wife.
