### ISSUE TITLE
Lab 3.04 - Second Example (cats and dogs)

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#60]
The code does work. In Python, variables that are only referenced inside a function are implicitly global. If a variable is assigned a new value anywhere within the function’s body, it’s assumed to be a local. If a variable is ever assigned a new value inside the function, the variable is implicitly local, and you need to explicitly declare it as ‘global’.

My version (shows assignment defaults to local, your example show reference defaults to global:

var_1 = 'cat'
var_2 = 'dog'

def print_out_my_favorite(favorite_pet):
    var_1 = "sheep"
    var_2 = "goat"
    if favorite_pet == var_1:
        print("My favorite pet is the cat.")
    elif favorite_pet == var_2: 
        print("My favorite pet is the dog.")
    else:
        print ("I do not know your animal")

print_out_my_favorite("dog")
print (var_1 + "  " + var_2)

The variables var_1 and var_2 (on the left side of an assignment) inside the print_out_my_favorite default to local variables. When referenced they they default to global for the module.

**Comment by goldblatt** [comment]
alright i added a few more examples that show the different cases: 
1) global variables overwritten by local variables
2) global variables referenced before assignment in a function with a local variable
3) global variables used without issue

**Comment by normanbauer** [comment]
Thanks,  I know it is a subtlety,  but the good students will pick up on it.
