### ISSUE TITLE
Lesson 3.05  Oregon Trail

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#61]
They should have been coming to California, could have had the Donner Party Threat.
What about  native American, probably politically incorrect?
The real Oregon trail was 2,200 miles long and ran from Independence Missouri to Oregon City, Oregon, The Oregon and  California Trails shared the eastern leg and split at Fort Hall, Idaho(Wikipedia).  As you can see I love history and like to throw in interesting facts a la Sheldon Cooper on Big Bang.

Seriously, 
In Scheme/Rubric, Helth should be Health, Correctl should be Correctly.

You never specified when and how much food was to be consumed (rate of consumption could be a function of activity).

I am not quite sure how the "list of variables called user_data that will contain the health, food, miles, month, day, days_passed and more" is to implemented.  I would guess as a list of lists which would make the game interesting. 

Should they assume 30 days per month or change the month. day based on the calendar days in a month?

Unseriously, a la Susan
Hahahaha let them crawl through the mud to Oregon.

**Comment by normanbauer** [comment]
I was thinking the rate of food consumption could be a function of activity also.

**Comment by TEALS-IntroCS** [comment]
Let's do food as function of activity for extra credit.
The rest of these items are fixed already.
There is no list of lists. Rather, a series of global variables.

**Comment by goldblatt** [comment]
alright updated!
