### ISSUE TITLE
Lab 4.02 Hint

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#62]
You could also mention: 
          last item can be gotten by my_list[-1]
          second to last element: my_list[-2]
          third to last element: my_list[-3]

**Comment by TEALS-IntroCS** [comment]
Great tip for students!

**Comment by goldblatt** [comment]
I'm not sure if this is necessary in this lab. it's a useful tip, but it should probably go earlier. the earlier lessons are really full though.

**Comment by normanbauer** [comment]
Maybe add it as an instructor optional tip

**Comment by TEALS-IntroCS** [comment]
Actually - it probably makes sense in the context of the "reverse a list" extra credit problem. We'll add it as an optional tip there.

**Comment by TEALS-IntroCS** [comment]
Tip added below extra credit problem.
