### ISSUE TITLE
Lesson 4.04 Nested Lists and Looping and Oregon Trail

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#64]
Lists of Lists is not discussed until now, but it seems the Oregon Trail exercise uses this concept. Did miss something or should Oregon Trail be in this Unit?

**Comment by TEALS-IntroCS** [comment]
We've updated Oregon Trail to remove nested lists. It now uses a series of global variables instead of a list of lists.
