### ISSUE TITLE
Lab 4.04 - Replace schedule example with something more suited to lists of lists (shopping carts?)

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#65]
For the Schedule exercise, why not put the time of day (morning, afternoon,evening) in the list of lists and have the students look up the activities by name rather than index.  This would include validation of input by the use of the is in syntax. Perhaps this could be a bonus option.

**Comment by goldblatt** [comment]
okay switched this to using a shopping list.
