### ISSUE TITLE
Lesson 4.05  Quiz on computer?

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#66]
Are the students supposed to take the 4.05 quiz using the computer and submit? I would imagine that the programming would be done individually, not partnering.

**Comment by TEALS-IntroCS** [comment]
They are certainly meant to be done individually. Teachers can decide whether to do the quizzes on computer or by hand. By hand makes more sense if you are trying to prep kids for AP CS A.
