### ISSUE TITLE
Lesson 4.06 Tic-Tac-Toe

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#67]
Should the spec specify the game board be updated and redisplayed after each move?

I imagine it would look like (this editor seems to add an extra line between lines):

O |    |  X

---

```
|    | O
```

---

X |     | O

**Comment by TEALS-IntroCS** [comment]
Yes, the spec should specify that the updated board be displayed on each turn.

**Comment by goldblatt** [comment]
this is already in the spec, but I added it in to the rubric
