### ISSUE TITLE
Lab 5.01 Earsketch -0 getting started

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#69]
I am guessing that to open Earsketch you go to the link:
http://earsketch.gatech.edu/earsketch2/#/development/

However I get :
Error message] ExternalError: SyntaxError: Unexpected token < on line 8
 line 8 contains:

from earsketch import \* 

I am at a loss as how to proceed. PS I have a tin ear and no rhythm.

**Comment by normanbauer** [comment]
You need a password to access the teacher material for Earsketch.

**Comment by normanbauer** [comment]
I went to http://earsketch.gatech.edu/earsketch2/ and was able to get a successful run, but no sound yet.  Am still playing with it.

**Comment by normanbauer** [comment]
Hey I got the following to play (don't think Adele would sign to it, maybe a rapper)

# python code

# script_name:

#

# author:

# description:

#
from earsketch import \* 

init() 
setTempo(140)
var1 = DUBSTEP_BASS_WOBBLE_007
var2 = DUBSTEP_PAD_003
var3 = DUBSTEP_DRUMLOOP_MAIN_005
var4 = DUBSTEP_LEAD_004
fitMedia(DUBSTEP_LEAD_003, 1, 1, 13)

setEffect(1, DELAY, DELAY_TIME, 500) 

finish()

**Comment by normanbauer** [comment]
Got the following to work and make sounds although I don't know what it does:

# python code

# script_name:

#

# author:

# description:

#
from earsketch import \* 

init() 
setTempo(140)
var1 = DUBSTEP_BASS_WOBBLE_007
var2 = DUBSTEP_PAD_003
var3 = DUBSTEP_DRUMLOOP_MAIN_005
var4 = DUBSTEP_LEAD_004
fitMedia(DUBSTEP_LEAD_003, 1, 1, 13)
fitMedia(var2, 1, 1, 13)
fitMedia(var3, 1, 1, 13)
fitMedia(var4, 1, 1, 13)

setEffect(1, DELAY, DELAY_TIME, 500) 

finish()

**Comment by normanbauer** [comment]
Found these instructions in Earsketch:
1. Sign in; make a new script: Make sure you are signed in. Open the Code Editor and click the "+" button to make a new script. Save your script to the cloud (under Options). As before, fill in the comments section of the script.
2. Add section comments: Add comments to show the structure of our code, like in the image above. #Setup should be directly above from earsketch import *. #Music should have a few empty lines under it for now, and #Finish should be directly above finish() . Remember that this is just to make your code easier for a human to read; comments (and empty lines) have no effect on how the program runs. 
3. Add fitMedia(): To add a sound clip to the DAW, we start by typing fitMedia() anywhere in the Music section.

By itself, fitMedia() doesn’t do anything; we need to also specify the clip name to add to our DAW, the track number to place the clip on, and the starting and ending points of our clip. In step 5, we will specify these details between the parentheses of fitMedia().
1. Choose a clip; paste it into fitMedia: Open the sound browser. Listen to a few clips using the play button, and pick one you like. We want to paste this clip’s name into fitMedia(). Click so that your cursor is inside of fitMedia()’s parentheses; back in the sound browser, click the paste button (clipboard) next to your chosen clip, and the clip name should be copied over. You should have something like fitMedia(Y18_DRUM_SAMPLES_2) in your script.
2. Choose a track, and start/end points: fitMedia() still needs a bit more information to do anything: 

After the clip name in the parentheses, type a comma, then the track number: 1.
Type another comma, then a start measure: 1.
Type another comma, then the end measure: 5.
You should have something like this: fitMedia(Y18_DRUM_SAMPLES_1, 1, 1, 5). A more general way to think about this is as fitMedia(clipName, trackNumber, startMeasure, endMeasure). Note that every piece of information in the parentheses MUST be separated by commas. 
1. Press Run and Play: Press Run to execute the script. Your chosen clip should be added to the DAW. Press play in the DAW and have a listen! If something isn't working, take a look at our example below and compare with your code:

**Comment by TEALS-IntroCS** [comment]
Lesson 5.01 should include a basic introduction to what EarSketch is, most notably **the URL to access it** must be included in the Do Now, Lesson and Lab!

**Comment by TEALS-IntroCS** [comment]
Could be done as a video.

**Comment by TEALS-IntroCS** [comment]
Patrick will flesh out Do-Now for 5.2 - 5.4

**Comment by osteenjp** [comment]
Done
