### ISSUE TITLE
Do now: Dictionaries 01 - sentence correction

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#72]
The sentence 

Write down what goes printed out. What type is my_dictionary?

should be

Write down what is printed out. What type is my_dictionary?

**Comment by TEALS-IntroCS** [comment]
Thanks- we haven't yet scrubbed units 5-8 for grammar/depth. @osteenjp 's work should cover this.
