### ISSUE TITLE
Lab 6.01 - Need has_key function

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#75]
Since an invalid entry in a dictionary throws an exception (which has not been discussed yet, you need the has_key function fro the dictionary data type to properly implement the lab. There should be a hint to look at the Python documentation to research the dictionary data type.

my_meme = {
    "ndb":"no big deal",
    "yolo":"You only live once"
    }
a = input("What meme do you want to look up?")
if (my_meme.has_key(a)):
    print( a + " : " + my_meme[a])
else:
    print ("sorry, " + a + " is not defined")
    # Add SQA
my_meme["SQA"] = "Synergy Quantum Academy"
print (my_meme)

**Comment by TEALS-IntroCS** [comment]
Great point. We need to give students the "has_key" method.

**Comment by osteenjp** [comment]
Done

**Comment by normanbauer** [comment]
I made an error here, has key has been deprecated in python 3

In fact has_key() was removed in Python 3.x. According to python docs: has_key() is deprecated in favor of key in d . Use dict.has_key() if (and only if) your code is required to be runnable by Python versions earlier than 2.3 (when key in dict was introduced).

Example:

2

d = {'a': 1, 'b': 2, 'c': 3}

if 'a' in d :
    print("It's there!")

# using not

if not 'a' in d :
    print("It's missing!")

**Comment by osteenjp** [comment]
Ok, will update to reflect that, thanks.

**Comment by osteenjp** [comment]
updated
