### ISSUE TITLE
Lab 6.02 Solution

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#77]
cat_string = 'Cats are cool. Baby cats are called kittens. cats make great pets.'
cat_string = cat_string.lower()
cat_string = cat_string.replace("."," ")
cat_list = cat_string.split()
print (cat_list)
cat_dict = {}
for x in cat_list:
    y = x.lower()
    if (not(cat_dict.has_key(y))):
        count = 0
        for check_word in cat_list:
            if (check_word == y):
                count =+ 1
    else:
        count = cat_dict.get(y)
        count = count + 1
    cat_dict[y] = count
print (cat_dict.items())
check_word = input('What word would you like to know the frequency of?')
if (not(cat_dict.has_key(check_word))):
    print ("'"+ check_word + "'" + ' does not occur ')
else:
    print ("'"+ check_word + "'" + ' occurs ' + str(cat_dict[check_word]) + ' times')

**Comment by goldblatt** [comment]
@TEALS-IntroCS Can you put this into sharepoint and then delete this so solutions aren't on GIT. :)

**Comment by normanbauer** [comment]
I don't know how to put it on sharepoint.  Thank you so much for saying I am super, it made my day, week and month.

**Comment by goldblatt** [comment]
hahahaha all in a day's work. thanks so much for all your comments-- they have been so helpful! i've put it in sharepoint (the password protected Microsoft website we are hosting the project/quiz/solution files on so that students can't see the answers on the git) and added a link

**Comment by goldblatt** [comment]
I'm going to close this!
