### ISSUE TITLE
Lesson 6.3 Instructor's Notes Cleanup

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#78]
Item 2 contains:
1. Lesson
   "Ask the students about part 1 of Do Now
   What type is list_dictionaries. It is still a dictionary type which goes from string to list. Dictionaries can also go from numbers to lists or numbers to strings any combination.
   Asks students about part 2 of the Do Now.
   How do you update a value within a dictionary. Have to first get the item. If it doesn't exist set it to empty. If it does exist append a value to the end.
   Have students practice adding and removing values from a dictionary that goes from strings to lists."

Should read:
1. Lesson
   "Ask the students about part 1 of Do Now
   What type is the list_dictionaries object? It is a dictionary type that has strings as keywords and lists as values.  Dictionary values can be of any type, while key words must be immutable (cannot be changed such as constants and tuples), key words are usually strings or integers.
   Ask students about part 2 of the Do Now.
   How do you update a value within a dictionary? In an assign statement, use the keyword and the new value. You can check to see if the key exists first with the has_key function, if the key exists the value is replaced; otherwise the key word, value pair is added to the dictionary.
   Have students practice adding and removing values from a dictionary that goes from strings to lists."

**Comment by TEALS-IntroCS** [comment]
Thanks-
Units 5-8 haven't yet been scrubbed for grammar and detail. This is a scheduled part of @osteenjp 's work over the next month or so.
