### ISSUE TITLE
Python versions, Cloud9 = 2.7.6 (default, Jun 22 2015, 17:58:13), python3 = 3.4.3 (default, Oct 14 2015, 20:28:29)

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#79]

**Comment by normanbauer** [comment]
I was trying the DoNow for 6.04 and noticed the type returned for dictionary_list.key() was different
1. in the interactive mode (python3) the type returned was <class 'dict_keys'> 
2. in the Cloud9 window, the type returned was <type 'list'>

I thought this is getting curiouser and curiouser like I fell though the Looking Glass.
I printed the versions on both and was surprised that the Cloud9 version was 2.7.6 and the interactive (python3) version was 3.4.3.

This explains why I get inconsistent results running the same code in different modes.
The Tower of Babylon all over again.

**Comment by TEALS-IntroCS** [comment]
@normanbauer I don't understand your comment. When you refer to interactive mode vs Cloud9 window are you referring to the interactive mode within Cloud9 or to a separate Python interpreter outside of Cloud9?

Please reopen the issue when you have replied to this comment.

**Comment by normanbauer** [comment]
The request refers to the facts that (as I have since discovered) that:
1. in the interactive (terminal mode), when you execute python3 you get version 3.4.3 of Python
2. the default version used by in the file pane is version 2.7.6 of Python
3. the // operators behave differently in Python 2 and 3.
4. the has_key function does not exist in Python 3

# I had to make a few changes to my solution to the cat dictionary exercise:

import sys
print (" version" + sys.version)
cat_string = 'Cats are cool. Baby cats are called kittens. cats make great pets.'
cat_string = cat_string.lower()
cat_string = cat_string.replace("."," ")
cat_list = cat_string.split()
print (cat_list)
cat_dict = {}
for x in cat_list:
    y = x.lower()
    if (cat_dict.get(y) != "None"):
        count = 0
        for check_word in cat_list:
            if (check_word == y):
                count += 1
    else:
        count = 0
        count = int(cat_dict.get(y))
        count = count + 1
    cat_dict[y] = count
print (cat_dict.items())
check_word = input('What word would you like to know the frequency of?')
if (cat_dict.get(check_word) == "None"):
    print ("'"+ check_word + "'" + ' does not occur ')
else:
    print ("'"+ check_word + "'" + ' occurs ' + str(cat_dict[check_word]) + ' times')

**Comment by normanbauer** [comment]
The has_key function is replaced by the get(dict) == "None"
