### ISSUE TITLE
Solution for Do Now 6.04  for python2 with a comment for python3

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#80]
import sys
print (sys.version)
my_dict = {
    'a':1,
    'b':2,
    'c':3,
    'd':4

```
}
```

print (my_dict.keys())
my_keys = my_dict.keys()
print(type(my_keys))
print (my_keys)
my_list = list(my_keys)
print (my_list)
for x in my_keys:
    print (x)

The python3 version needs to cast my_keys as list to work (tricky question)

**Comment by TEALS-IntroCS** [comment]
You don't need to cast the dict_keys object to a list to use it as an integrator in a loop. dict_keys objects are iterable. If you just do "for x in my_keys" it works fine. Actually, in your code above, you did this inadvertently!
