### ISSUE TITLE
Lab 6.04 Solution

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#81]
def max_value():
    max = -1
    max_key = ""
    all_keys = cat_dict.keys()
    for x in all_keys:
        key_value = cat_dict.get(x)
        if (key_value > max):
            max = key_value
            max_key = x
    print (" Max Value = " + str(max) + " key = " + max_key)
    del cat_dict[max_key]

cat_string = 'Cats are cool. Baby cats are called kittens. cats make great pets.'
cat_string = cat_string.lower()
cat_string = cat_string.replace("."," ")
cat_list = cat_string.split()
print (cat_list)
cat_dict = {}
for x in cat_list:
    y = x.lower()
    if (not(cat_dict.has_key(y))):
        count = 0
        for check_word in cat_list:
            if (check_word == y):
                count =+ 1
    else:
        count = cat_dict.get(y)
        count = count + 1
    cat_dict[y] = count
print (cat_dict.items())
check_word = input('What word would you like to know the frequency of?')
if (not(cat_dict.has_key(check_word))):
    print ("'"+ check_word + "'" + ' does not occur ')
else:
    print ("'"+ check_word + "'" + ' occurs ' + str(cat_dict[check_word]) + ' times')

max_value()
max_value()
max_value()
max_value()

**Comment by goldblatt** [comment]
this is super helpful, but could you hold off on posting the solutions.I'm not sure how to hide this so students could feasible see it! @TEALS-IntroCS maybe Norman could email files to you and you can post onto the sharepoint and add links.

**Comment by TEALS-IntroCS** [comment]
Great suggestion. 
We don't want to post solutions or tests/quizzes in GitHub because it is publicly viewable on the internet. If you send me solutions by email (nathaniel@tealsk12.org) or to the Intro Squad, we can put them in a file and store them in the SharePoint site where we currently have the project solutions and quizzes.

Once we've done so, we should delete this thread.
