### ISSUE TITLE
Lesson 6.04  Suggested text changes

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#82]
Lesson
Ask the students about part 1 of Do Now
What type is returned. How can lists be used with a for loop.
Asks students about part 2 of the Do Now.
Ask students to write their solution no the board.
Disucss that it is possible to do just for key in my_dictionary..., but this behind the scenes is similar to calling the keys function.
Discuss that the order is not exactly what was expected.
Unlike lists dictionaries have no guaranteed order

Should be

Lesson
->Ask the students about part 1 of Do Now   (ask what, should be some specific thing(s))
->What type is returned? How can lists be used with a for loop?
Asks students about part 2 of the Do Now.
->Ask students to write their solution on the board.
-.>Discuss that it is possible to do just for key in my_dictionary..., but this behind the scenes is similar to calling the keys function.
Discuss that the order is not exactly what was expected.
Unlike lists dictionaries have no guaranteed order
# 

Is Discuss that a good construct? It somehow does not sound right to me.

**Comment by normanbauer** [comment]
I was thinking instead of "Discuss that", maybe use "Discuss : ".  Just a suggestion.

**Comment by TEALS-IntroCS** [comment]
Thanks. Units 5-8 haven't yet been scrubbed for grammar/depth. This is part of @osteenjp 's ongoing work for the next month.
