### ISSUE TITLE
Lesson 7.01 Linked example

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#83]
I don't know if the example was meant to be executed, but if it was it should look like:
# Example
#1. Read the following code:
# ```

class Pet(object): 
    """Represents a pet"""

my_pet_1 = Pet() 
my_pet_1.type = 'cat'
my_pet_1.noise = 'meow'
my_pet_1.full_name = 'Snuffles McGruff'

my_pet_2 = Pet()
my_pet_2.type = 'cat'
my_pet_2.noise = 'meow'
my_pet_2.full_name = 'Snowpounce Flury'

my_pet_3 = Pet()
my_pet_3.type = 'cat'
my_pet_3.noise = 'meow'
my_pet_3.full_name = 'Snickers Snorkel'

my_pets = [my_pet_1, my_pet_2, my_pet_3]
print(type(my_pets))
for pet in my_pets: 
    print(pet.full_name)
# ```
# 

I added the print(type(my_pets)) just as good to know

**Comment by normanbauer** [comment]
Here is a more complete example

# Example

#1. Read the following code: 

#```
class Pet(object): 
    """Represents a pet"""
class Element:
    def **init**(self,name,symbol,number):
        self.name = name
        self.symbol = symbol
        self.number = number
    def **str**(self):
        return "{} : {}\nAtomic Number : {} \n".format(self.name,self.symbol,self.number) 
hyd = Element("Hydrogen","H","1")
print (hyd)

my_pet_1 = Pet() 
my_pet_1.type = 'cat'
my_pet_1.noise = 'meow'
my_pet_1.full_name = 'Snuffles McGruff'

my_pet_2 = Pet()
my_pet_2.type = 'cat'
my_pet_2.noise = 'meow'
my_pet_2.full_name = 'Snowpounce Flury'

my_pet_3 = Pet()
my_pet_3.type = 'cat'
my_pet_3.noise = 'meow'
my_pet_3.full_name = 'Snickers Snorkel'

my_pets = [my_pet_1, my_pet_2, my_pet_3]
#print(my_pet_1())
print(type(my_pets))
for pet in my_pets: 
    print(pet.full_name + " Type " + pet.type + " Noise " + pet.noise)
#```

**Comment by TEALS-IntroCS** [comment]
Thanks!

**Comment by kenneychan** [comment]
The line printing the my_pet list has been removed to match the do now.  Subsequent lessons in Unit 7 goes over the constructor for Python classes.
