### ISSUE TITLE
Changing Cloud9 (file mode) to use Python3 in File Mode, Cleaning up Tabs

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#84]
Cloud9 Python defaults to Python 2.7.6. It can be changed to use Python 3.4.3 by doing the following:
1. Right mouse click on the Run button at the top of the Cloud9 Python window
2. Select Manage... from the pull down that appears
3. On the Project Settings window that appears, scroll down to Language Support 
4. On the scroll list that appears to the right of the heading Python Version:, select the Python 3 entry
5. Exit the Preferences Tab on the line right below top line starting with Cloud9 and containing the Run button.
6. Both the file and interactive tabs should be cleaned up by regularly deleting the tabs by selecting the x on the right side of the tab name.

**Comment by goldblatt** [comment]
okay added this to the editor sign up sheet
