### ISSUE TITLE
Python Formatting Specifications and Alternatives to the Music Unit

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#85]
I think it would be a good idea to have a section on the formatting of output including the format statement and some of the formatting specification.  This would be of great benefit.

The discussion would not have to be complete, just a good intro.  It would be good to do some file i/o.  Perhaps a unit with these two subjects would be a great alternative to the music unit.

Also as another alternative, having a Unit on building apps would be a great selling point to Administrators and Educators. As a guy I worked with said, presenting flashy sexy apps is a great selling point to students as well.  I think this would be a great benefit to TEALS, the students and everyone.

**Comment by TEALS-IntroCS** [comment]
We're open to incorporating additional optional units, either within the GitBook if they are written to the same level of detail, or in the SharePoint repository if they are less complete. However, right now we do not have the capacity to develop these units ourselves.
