### ISSUE TITLE
How will TEALS handle teacher training for Python

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#87]
Will TEALS provide teacher training over the summer?  Especially for teachers who have little or no previous computer science background?

**Comment by TEALS-IntroCS** [comment]
This is not an actionable curriculum issue.
The model for 2nd semester intro is no different from 1st semester. The primary method of PD in the TEALS program is learning by doing in the classroom. Teachers are should attempt the curriculum assignments/projects ahead of the students and get feedback from the volunteers the first time around. The 2nd time around they should attempt to teach the topics with support from the volunteers.
