### ISSUE TITLE
Use themes to get better indentation/line number viewing

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#88]
With the default View->Themes the line numbers and indentation bars are not very readable.  I found that using the Cobalt allows theses items to standout much better. Other combinations work well also. It is interesting, the colors of python key words and literals, etc. change depending on what Theme you choose.

**Comment by TEALS-IntroCS** [comment]
We'll mention this in the video we create to show the features of the IDE in bug #44 .
