### ISSUE TITLE
Python 2 versus Python 3 Disclaimer

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#89]
I think we should have a disclaimer

Python is an evolving language. Python 3 is  major upgraDe to the language, released in 2010. There is a lot of existing software written under Python 2 and there is resistance to upgrading to Python 3 due to code breakage and cost. Just as a car part from a 10 year old model car will probably not fit a new model of the same car, Python 2 code probably not run run in a Python 3 environment.  In Python 3 there are new features, significant upgrades "underneath" which makes the code run better and/or faster as well as no longer supporting (deprecating) some Python 2 capabilities.  When looking at Python code, be careful to note whether it is Python2 or Pynton3.

This class will use Python 3.

**Comment by TEALS-IntroCS** [comment]
Added to Introduction.
