### ISSUE TITLE
Final Project Development Plan & Organizer aren't found

### ISSUE THREAD

**Issue by bensk** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#96]
😭

**Comment by TEALS-IntroCS** [comment]
Hey there-
Unit 8 is still being cleaned up and we're tracking this separately. We'll have it ready to go by the midpoint of the semester. That said, it's mostly just a copy of the 1st semester final project unit. We'll have updated dev-plan/organizer docs to account for the differences b/w SNAP and Python.

**Comment by kenneychan** [comment]
The final project links have been fixed.
