### ISSUE TITLE
Lab 2.04 b is not defined 

### ISSUE THREAD

**Issue by bensk** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#99]
Am I missing something [here](https://teals-introcs.gitbooks.io/2nd-semester-introduction-to-computer-science-pri/content/units/2_unit/04_lesson/lab.html)? b is undefined: 

``` python
    a = 100
    difficulty_level= 7
    if a > 85 and b > 7:
        print("Stellar Grade")
    elif a <= 85 and b <= 7: 
        print("okay grade")
    else: 
        print("pretty good grade")
```

**Comment by BossJ** [comment]
Looks like it was supposed to be 'difficulty_level' not 'b', proposed the change!

**Comment by TEALS-IntroCS** [comment]
To match the rest of the lesson 'difficulty_level' has been changed to 'b'
